name: ghpages build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - react/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.9.0]

    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd ./react
          npm i
          npm run build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: react/dist
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
